# Generated by Django 6.0 on 2026-01-03 09:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                ("active", models.BooleanField(default=True)),
                ("timestamp_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "User"), (2, "Assistant"), (3, "Tool")], default=1
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Context",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "User"), (2, "Assistant"), (3, "Tool")], default=1
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("timestamp_on", models.DateTimeField(auto_now_add=True)),
                (
                    "chat_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contexts",
                        to="website.chatsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("content", models.TextField()),
                ("timestamp_on", models.DateTimeField(auto_now_add=True)),
                ("categories", models.ManyToManyField(to="website.category")),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="website.prompt",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="sections",
            field=models.ManyToManyField(to="website.section"),
        ),
    ]
