# Generated by Django 6.0 on 2026-01-03 09:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatsession",
            old_name="created_on",
            new_name="timestamp_on",
        ),
        migrations.RemoveField(
            model_name="chatsession",
            name="updated_on",
        ),
        migrations.AddField(
            model_name="chatsession",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="uid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="prompt",
            name="chat_session",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.chatsession",
            ),
            preserve_default=False,
        ),
    ]
