# Generated by Django 6.0 on 2026-01-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_rename_created_on_chatsession_timestamp_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="context",
            name="prompts",
            field=models.ManyToManyField(to="website.prompt"),
        ),
        migrations.AddField(
            model_name="prompt",
            name="contexts",
            field=models.ManyToManyField(to="website.context"),
        ),
        migrations.AddField(
            model_name="prompt",
            name="extra",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Holds things like thinking or tool info",
            ),
        ),
    ]
