# Generated by Django 6.0.1 on 2026-01-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_context_prompts_prompt_contexts_prompt_extra"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="suggested_consultation",
            field=models.BooleanField(default=False),
        ),
    ]
