# Generated by Django 6.0.1 on 2026-01-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_chatsession_suggested_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='thinking',
            field=models.TextField(blank=True, default='', help_text='Holds the LLM thinking process if any'),
        ),
    ]
