# Generated by Django 6.0.1 on 2026-01-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_prompt_thinking'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='profile',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='type',
            field=models.IntegerField(choices=[(1, 'User'), (2, 'Assistant'), (3, 'Tool'), (4, 'None')], default=4),
        ),
    ]
